### ISSUE TITLE
Gradle plugin idea?

### ISSUE THREAD

**Issue by nedtwigg** [wizawu/1c#1]
If I want to use Java in a Typescript environment, [jsweet](http://www.jsweet.org/) is a great option.

If I want to call Java jars from a Typescript environment, this project is a great option.

But what if I want to write Typescript in a Java environment?  Java build system, java deps, I just want to create a .jar with some Java shim code and bundled javascript?  This project looks like the start of a great option for that usecase.

Feel free to close, just wanted to toss it out there :)

**Comment by wizawu** [comment]
Thank you very much! I am maintaining this project for a long-term and already use it in production. I am glad more ppl aware of it.

I love Java, Kotlin and TypeScript. The original purpose of this project is to avoid writing "duplicate" code (like model definitions) for back-end (e.g. Kotlin) and front-end (e.g. TypeScript). So I decided to translate one to another, which now is from `.jar` to `.d.ts`.

The project is mainly consist of a translator and a compiler (webpack). If you are using Java build system, 1c is not helping.

> I just want to create a .jar with some Java shim code and bundled javascript

The way I propose with 1c is, to create a npm package. For example, if you wanna create a wrapper on MySQL JDBC which can be used in TypeScript, the `package.json` is like

```
{
  "name": "mysql-jdbc-nedtwigg",
  "version": "0.0.1",
  "mvnDependencies": [
    "mysql:mysql-connector-java:6.0.6"
  ]
}
```

Then `npm publish`. And in your 1c (not Java) project, you can import the wrapper in `package.json` like

```
{
  "dependencies": {
    "mysql-jdbc-nedtwigg": "0.0.1"
  }
}
``` 

Now you can see another usage of 1c - to unify the dependency management of Java and Node.

**Comment by nedtwigg** [comment]
That looks awesome, but it doesn't work for users who have a big Java project and can't easily switch the build system.  Here's my dream gradle plugin:

```
plugins {
  id 'com.wizawu.1c`
}

dependencies {
    typescriptDeps 'mysql:mysql-connector-java:6.0.6'
}

/src/main/java2typescript/
     Java code code here is available to Typescript
/src/main/typescript-defs/
    `ts.d` for typescriptDeps and java2typescript
/src/main/typescript/
     TypeScript code here
/src/main/typescript2java/
     Generated java shims to the TypeScript, implemented by nashorn
/src/main/java/
     Regular java code that can see java2typescript and typescript2java
```

It's the difference between sneaking Java into an npm project (1c now) and sneaking Typescript into a Java project (what I'd like to do).

I think there are a lot of people with big Java codebases that are exploring a migration towards TypeScript.  It would be neat to be able to take a component and move it to TypeScript pain free.  Would definitely be a lot of work though :)

I've published a few gradle plugins ([spotless](https://github.com/diffplug/spotless) and [goomph](https://github.com/diffplug/goomph)).  If you could build the `typescript-defs` and `typescript2java` parts, I could wire the rest of it up.

**Comment by wizawu** [comment]
You've got a point here.

`/src/main/typescript2java/` This part is not that easy, for me at least.

But if you want to migrate Java to TypeScript without changing the Java code, I think it's feasible.

```
/src/main/java/
    Current source code
/src/main/java2typescript-defs/
    Generate typescript definition from Java
/src/main/typescript/
    New source code
```

The problem is, you cannot call TypeScript from Java. But still you can call all the APIs implemented in Java from TypeScript (the new source code). I can build the `java2typescript-defs` part. It might not be close to what you need, but that's the furthest I get.

**Comment by wizawu** [comment]
One more thing is, if you want to switch to TypeScript while reusing Java, the TypeScript definition of Java code is all you need. You don't need to translate Java to TypeScript line by line.

But if you want to use Java and TypeScript together (like Java and Kotlin), that's the problem I haven't solved.

**Comment by nedtwigg** [comment]
Ahhh, I see.  As I think more about it, implementing `typescript2java` is very difficult.

Looks like that's the whole thrust of [DukeScript](https://github.com/dukescript/maven-typings-plugin), which is a big dual-licensed behemoth (GPL or pay-for-commercial).

The trouble is, unless the Main is called from TypeScript, then it's tricky to integrate into a larger project.  Generally, the main would be the last thing to migrate.

Your project is super cool!  I'll be ruminating on if there are any good workarounds...
