### ISSUE TITLE
Long Build Times

### ISSUE THREAD

**Issue by mfreeman-xtivia** [wizawu/1c#10]
I can't tell you just how awesome this tool is---the only "oh man I wish it were better" for me is how long "1c build" takes even for the simple examples.

Any thoughts on why that is? Any thing I could do in terms of extra memory allocation or some such to make the build take a little less time?

Again thanks for a kick-butt tool---I've been dying for something like this to show up on the server side for a long time now

**Comment by Egoscio** [comment]
In #7, @wizawu mentioned:
> If you are sure the TypeScript source code is written without syntax error, you can use 1c build --skipJDK to skip checking TypeScript Definition of JDK, which can reduce a lot of compilation time.

**Comment by mfreeman-xtivia** [comment]
Understood.

But I am hoping for a more general solution, similar in my experiences in the past with something like the GWT compiler, where if you have it, you can trade extra memory at compile time for reduced compile times, in cases where i may or may not know if the code is going to compile cleanly or not.

**Comment by wizawu** [comment]
I think this issue is quite related to #9 . The slow compilation is caused by checking those large .d.ts files.

I am also very annoyed by this when I am trying to deploy a new version of daemon/website online. When we used Python/Node/Go before, it took less than one minute. But now we have to wait 2-3 mins for `1c build`.

So I will try fix that, along with #9 .

**Comment by wizawu** [comment]
@mfreeman-xtivia @Egoscio 
Please try this example with `1c@8.15.1`

``` typescript
// test.ts
java.lang.System.out.println($ENV.PWD)
```

The compilation time has been reduced from 6.4s to 3.8s.

**Comment by wizawu** [comment]
Great news! I just added `fork-ts-checker-webpack-plugin` to speed up builds.

I just tried everything ts-loader [recommended](https://github.com/TypeStrong/ts-loader#faster-builds) including
- fork-ts-checker-webpack-plugin
- happypack
- thread-loader/cache-loader

The latter two didn't seem to have significant optimization. Luckily, with `fork-ts-checker-webpack-plugin` added to 1c, we can already reduce the build time to 50% (122s -> 55s).

But please notice that for small projects (like building single ts file), the build time is still at least 5 seconds or so (Mostly costed by compiler bootstrap).
