### ISSUE TITLE
Is the project backed by a company?

### ISSUE THREAD

**Issue by sledorze** [wizawu/1c#12]
Is the project backed by a company?
Maybe it would be a great endorsement to know the company using it in production and for what more specific usage.

**Comment by wizawu** [comment]
Is the project backed by a company?
- No, it's a personal project.

But it's used in our internal and client's production environment.

**Comment by sledorze** [comment]
@wizawu I think that's something people coming to the repo want to know more about as it can positively impact the viability of the project (or not).

**Comment by wizawu** [comment]
Surely it's not production-ready by now.
And when it's ready, I would provide more use cases, sample projects and list who are using it.
