### ISSUE TITLE
[Question]: AOP and Spring Boot possible?

### ISSUE THREAD

**Issue by Deviad** [wizawu/1c#13]
Hello,
I got interested into this project and I would like to know if it's possible to have annotations working with this.
Would it be possible also to use Spring Boot? 

Is it possible to have annotations?

Would the annotations be written into Typescript and then converted to AspectJ or what would be the process?

**Comment by wizawu** [comment]
> Is it possible to have annotations?

It is possible BUT requires re-implementation (in TypeScript) of the original annotations in Spring Boot. And I bet it takes tremendous effort.

Currently 1c just reuses all the JARs from JDK and 3rd-party libraries while generating TypeScript definitions for them.
