### ISSUE TITLE
Can't even run Hello World

### ISSUE THREAD

**Issue by Diluka** [wizawu/1c#2]
`java.lang.System.out.println("hello world")`

compile failed

I think there should be a complete example project.

**Comment by wizawu** [comment]
```
1c env
```

Please show me the screenshot of your build and the output of the command above.

**Comment by wizawu** [comment]
I just released a new version `8.6.4`. Please try again.

The previous error you encountered may be caused by the missing tsconfig.json. Now I will generate one automatically if it is not found.

**Comment by wizawu** [comment]
`1c` is designed to be as easy to use as possible. There is a consice tutorial here https://1c.wizawu.com/#/tutorial.

For your hello-world example,

```
npm install -g 1c
1c env        # optional, check if you have npm, gradle and java
vi main.ts    # java.lang.System.out.println("hello world")
1c build main.ts
1c run main.js
```

**Comment by Diluka** [comment]
thx
The default tsconfig.json generated by `tsc --init` is not work. After update, the tsconfig.json generated by 1c is OK.

**Comment by wizawu** [comment]
I just added several [examples](https://github.com/wizawu/1c/tree/master/examples).
