### ISSUE TITLE
Windows limitation

### ISSUE THREAD

**Issue by MouhamedAymen** [wizawu/1c#3]
I just wasted an hour trying to make this work under windows 10, before finding about the _slightly_ _hidden_  limitation in guideline [https://1c.wizawu.com/#/guideline](url). This really should be in home page and github readme.

I suggest creating a docker debian image with everything required to make it work, else I will try to setup one when i get some time.

I still didn't test it or see it in action, but this is really a cool project, an idea that can save many devs so much time 👍

**Comment by wizawu** [comment]
Thank you very much! I am so glad to hear that.

Actually I've already altered the code to adapt Windows and Mac. Can you show some screenshots or logs of the issues you ran into?

**Comment by wizawu** [comment]
> I just wasted an hour trying to make this work under windows 10

And I am sorry abt that...

**Comment by wizawu** [comment]
I have updated https://1c.wizawu.com/#/install
