### ISSUE TITLE
Production example

### ISSUE THREAD

**Issue by LucaGabi** [wizawu/1c#5]
Hi
    I find this project very useful, but it has little documentation on how to setup a production ready web application, can you help ? I see it uses nashorn javascript engine so it can use multiple threads for processing?

Thanks.

**Comment by wizawu** [comment]
> so it can use multiple threads for processing?

Yes.

---

You can go through the [installation steps](https://1c.wizawu.com/#/install) and [tutorial](https://1c.wizawu.com/#/tutorial), or follow my instructions (take ubuntu as an example) below.

### Installation

Install prerequisites,
```
sudo apt install nodejs gradle openjdk-8-jdk
```
Install 1c,
```
sudo npm -g install 1c@8.x.x
```

### Get started

If you're going to develop a web application, you can decide the project structure quite freely, such as the Django way. Here is my preference.

![image](https://user-images.githubusercontent.com/1676756/43001374-98fb0534-8c57-11e8-8fba-8c0f5b441981.png)

Edit `package.json`, you can put both NPM and Maven packages here.

You can choose other web frameworks, but you can **ONLY** use those can be used **WITHOUT** Java annotations. I will always recommend [Spark](http://sparkjava.com/) (@perwendel /[spark](https://github.com/perwendel/spark)).

```json
{
  "dependencies": {
    "@types/chalk": "^0.4.31",
    "chalk": "^1.1.3"
  },
  "mvnDependencies": [
    "com.sparkjava:spark-core:2.5.5"
  ]
}
```
Then in the same directory as `package.json`, run
```
1c install
```

![image](https://user-images.githubusercontent.com/1676756/43001624-755a8176-8c58-11e8-9bb7-a05975f8cb17.png)

Once it completes, you can see several new files/directories.
* lib/
* node_modules/
* package-lock.json
* tsconfig.json

![image](https://user-images.githubusercontent.com/1676756/43001811-3e0778fe-8c59-11e8-8701-bc58205498e2.png)

Now you can import the project directory to VS Code, which is the most friendly to TypeScript development. You can check the completed source code 
[1c-example.zip](https://github.com/wizawu/1c/files/2213862/1c-example.zip).

### Build and run

```
1c build src/main.ts
1c run main.js
```

![image](https://user-images.githubusercontent.com/1676756/43002383-1f32459c-8c5b-11e8-9835-3b1b34d1a5e7.png)
