### ISSUE TITLE
Using generated JS file outside 1c environment

### ISSUE THREAD

**Issue by mfreeman-xtivia** [wizawu/1c#6]
Is it possible to use the generated JS file outside the 1c environment, i.e. without using "1c run?"

Can i take the built JS file and just run it using jjs for example, or do i need some magic bits to make that work?

**Comment by wizawu** [comment]
If you use only standard JDK and NPM packages (**without**  Maven dependencies), you can run the JS output without `1c run`. For example,

![image](https://user-images.githubusercontent.com/1676756/43085698-36a5d552-8ece-11e8-8d06-7c136bfc52e9.png)

**Comment by wizawu** [comment]
And if the TypeScript source is for front-end, `1c build` just acts like webpack/gulp. You can use the generated JS file in `<script>` tag on HTML pages.

**Comment by mfreeman-xtivia** [comment]
And presumably in the first case even if i used Maven dependencies, if i include all of the dependent JARs on the "jjs" command line (using -cp option) then that should work too right?
