### ISSUE TITLE
[Feature Request] Fragment TypeScript definitions into multiple files for fat jars

### ISSUE THREAD

**Issue by Egoscio** [wizawu/1c#9]
I have a 45mb fat jar loaded with dependencies. When I loaded the fat jar into 1c, the resulting type definitions were 29mb. The definitions were so big, Visual Studio Code never managed to parse them in time for IntelliSense features. For the time being, I'm trying to find a "non-fat" (?) jar artifact. In the long run, it would be great if 1c could fragment fat jar definitions into a folder with multiple type definition files. Then, in your TypeScript files, you can individually import whatever dependencies you need. What are your thoughts on this?

Thank you.

**Comment by wizawu** [comment]
> fragment fat jar definitions into a folder with multiple type definition files

Feasible.

> individually import whatever dependencies you need

Need a second thought.
